fix: mailchimp not giving 404's

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,10 +18,14 @@ jobs:
       - name: Check if edition exists
         id: check-edition
         run: |
-          if wget --spider "https://mailchi.mp/hackernewsletter/${{steps.determine-edition.outputs.EDITION}}" 2>&1 | grep -q "200 OK"; then
+          if wget -qO- "https://mailchi.mp/hackernewsletter/${{ steps.determine-edition.outputs.EDITION }}" | grep -q "trying to reach a page that was built by Mailchimp bu"; then
+            echo "Mailchimp page not found, exiting workflow."
+            exit 1
+          elif wget --spider "https://mailchi.mp/hackernewsletter/${{ steps.determine-edition.outputs.EDITION }}" 2>&1 | grep -q "200 OK"; then
             echo "Edition exists, continuing workflow."
           else
-            echo "Edition does not exist, exiting workflow." && exit 1
+            echo "Edition does not exist, exiting workflow."
+            exit 1
           fi
 
       - name: Setup Python
