Added features & Automatic newspapers (#5)
* feat: add download folder instead of spitting in main directory

* feat: add some more icons

* feat: implement base url handling

* feat: combine photo scraping & html downloading in one

* feat: youtube data downloader

* feat: pdf data extractor

* feat: make workflow check for tags

* chore: add new deps

* fix: bad chatgpt flow

* fix: idk what github is doing

* fix: try to use new workflow syntax thingy

* fix: try this

* feat: try this

* fix: try pulling

* fix: try some magic

* fix: try some magic

* fix: remove the $edition

* fix: mailchimp not giving 404's

* fix: use github output

* fix: tectonic being funny

* feat: skip action

* fix: syntax

* fix: make it a draft

* fix: remove draft

* feat: create schedule to workflow

* fix: workflow not getting the latest tag

* feat: github handler

* feat: update workflow to check for latest edition

* fix: edition not being put into env no more

* fix: syntax again

* fix: it not working on this weeks pdf

* chore: update all action versions

* fix: make python also use version 20 node

* style: deduplicate a bit of code

* style: a bit more code shortening

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,54 +1,96 @@
 on:
   workflow_dispatch:
+  schedule:
+     - cron: '0 6 * * *'
+
+
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: checkout repo content
-        uses: actions/checkout@v3
+      - name: Checkout repo content
+        uses: actions/checkout@v4
+
+      - name: Setup Python
+        uses: actions/setup-python@v5.0.0
+        with:
+          cache: "pip"
       
-      - name: setup python
-        uses: actions/setup-python@v4.7.0
-      
-      - name: install python packages
+      - name: Install Python packages
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
+      
+      - name: Determine next edition
+        id: determine-edition
+        run: |
+          git fetch --tags
+          git fetch origin --tags
+          latest_git_tag=$(($(git tag | sort -n | tail -n 1)))
 
-      - name: setup playwright
+          # Get the latest edition from Python script
+          latest_edition=$(python get_latest_edition.py)
+
+          if [ $? -eq 1 ]; then
+            echo "Error: Unable to get the latest edition. Exiting..."
+            exit 1
+          fi
+
+          # Compare the outputs
+          if [ "$latest_git_tag" -eq "$latest_edition" ]; then
+              echo "Latest Git tag and latest edition are equal. Exiting workflow."
+              exit 1
+          else
+              echo "Latest Git tag and latest edition are not equal. Continuing workflow."
+              # Continue with your workflow commands here
+          fi
+          echo "EDITION=$latest_edition" >> "$GITHUB_OUTPUT"
+      - name: Check if edition exists
+        id: check-edition
+        run: |
+          if wget -qO- "https://mailchi.mp/hackernewsletter/${{ steps.determine-edition.outputs.EDITION }}" | grep -q "trying to reach a page that was built by Mailchimp bu"; then
+            echo "Mailchimp page not found, exiting workflow."
+            exit 1
+          elif wget --spider "https://mailchi.mp/hackernewsletter/${{ steps.determine-edition.outputs.EDITION }}" 2>&1 | grep -q "200 OK"; then
+            echo "Edition exists, continuing workflow."
+          else
+            echo "Edition does not exist, exiting workflow."
+            exit 1
+          fi
+
+      - name: Setup Playwright
         run: playwright install chromium
 
-      - name: execute py script
-        run: python generator.py ${{ vars.HN_ISSUE }}
+      - name: Execute Python script
+        run: python generator.py ${{steps.determine-edition.outputs.EDITION }}
 
-      - name: setup Tectonic 
-        uses: WtfJoke/setup-tectonic@v2.1.1
+      - name: Setup Tectonic 
+        uses: WtfJoke/setup-tectonic@v3
         with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Print Tectonic version
         run: tectonic --version
 
-      - name: run Tectonic
+      - name: Run Tectonic
         run: tectonic output.tex
 
       - name: Rename output.pdf
-        run: mv output.pdf HackerNewsPaper-${{ vars.HN_ISSUE }}.pdf
+        run: mv output.pdf HackerNewsPaper-${{ steps.determine-edition.outputs.EDITION }}.pdf
 
       - name: Upload a Build Artifact
         if: always()
-        uses: actions/upload-artifact@v3.1.2
+        uses: actions/upload-artifact@v4.3.1
         with:
           path: ./*.*
 
       - name: Create release
-        uses: ncipollo/release-action@v1.13.0
+        uses: ncipollo/release-action@v1.14.0
         with:
           allowUpdates: true
-          tag: ${{ vars.HN_ISSUE }}
-          name: "HackerNewsPaper #${{ vars.HN_ISSUE }}" 
-          body: "HackerNewsPaper #${{ vars.HN_ISSUE }}"
-          artifacts: "HackerNewsPaper-${{ vars.HN_ISSUE }}.pdf"
+          tag: ${{ steps.determine-edition.outputs.EDITION }}
+          name: "HackerNewsPaper #${{ steps.determine-edition.outputs.EDITION }}" 
+          body: "HackerNewsPaper #${{ steps.determine-edition.outputs.EDITION }}"
+          artifacts: "HackerNewsPaper-${{ steps.determine-edition.outputs.EDITION }}.pdf"
           removeArtifacts: true
-          
